/// Flutter icons GridIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GridIcons
///      fonts:
///       - asset: fonts/GridIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GridIcons {
  GridIcons._();

  static const _kFontFam = 'GridIcons';
  static const _kFontPkg = null;

  static const IconData cash_app = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dayflash = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devianart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribble = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emai = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messenger = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pintrest = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qq = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quora = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qzone = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound_cloud = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData the_dots = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tiktok = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upi = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venom = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viber = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watsapp = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wechat = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wikkipedia = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xbox = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yelp = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtub = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData artstation = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baidu_tieda = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_1 = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData professional = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vendor = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData all = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clients = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personal = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData duplicate = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData excahnge = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
